// Re-export all schemas
export * from "./common.js";
export * from "./products.js";
export * from "./orders.js";
export * from "./customers.js";
export * from "./inventory.js";
export * from "./analytics.js";
export * from "./discounts.js";
export * from "./collections.js";
export * from "./shop.js";
export * from "./themes.js";
